### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HazCod**
Added OpenELEC installation instructions.

### CODE REVIEW

**Comment by HazCod** [comment]
OpenELEC forum topic: http://openelec.tv/forum/12-guides-tips-and-tricks/76298-how-to-setup-limelight-on-the-raspberry-pi#137002

**Comment by kaasszje** [comment]
I am curious how to make a start for this script inside kodi ?
Can't seem to get it to work (allready tried to make python script to start something simulair as run.sh)
However it just shutsdown kodi then restarts kodi.

**Comment by HazCod** [comment]
I will let you know @kaasszje when I find advanced launcher.

**Comment by kaasszje** [comment]
tnx :)

2015-04-02 14:55 GMT+02:00 HazCod <notifications@github.com>:

**Comment by stsfin** [comment]
These guides for making limelightscripts for kodi should help
http://forum.osmc.tv/showthread.php?tid=16517

**Comment by HazCod** [comment]
Added instructions in the OE forum topic for x68 systems.

**Pull request closed without merging**
