### PR TITLE
Add: platform model detection. Workaround for C1 H264 1080p decoding …

### PR DESCRIPTION
**Pull request by AreaScout**
**Description**

small change since we are going upstream

**Purpose**

ODROID-C1 had some issues with 1080p decoding, there is a board detection now and a fix for 1080p only for this board

### CODE REVIEW

**Comment by irtimmer** [comment]
If [interpreted correctly](http://forum.odroid.com/viewtopic.php?p=130510#p130510) this is only required for older linux kernel versions (3.10)?

**Comment by AreaScout** [comment]
Hi, yes you are absolutely right, it seem's that this is only related to our 3.10 kernel and the Amlogic implementation there, but as i do not know any other open source Amlogic Linux kernel implementation i think we can merge this as for now.

/play story

**Comment by AreaScout** [comment]
do not confuse you 3.10 is ODROID-C1 and 3.14 ist ODROID-C2

**Comment by irtimmer** [comment]
I think it's much cleaner to do the check based on kernel version than on parsing cpuinfo. Therefore this patch has been replaced by 6fcc63ee9ea7660080de985ef07931418b6e2183

**Comment by AreaScout** [comment]
If we will ever see a higher kernel version for ODROID boards this will make sense ^^ 

thank you for merge an reviewing the code !

**Pull request closed without merging**
