### PR TITLE
Add OMX Audio support

### PR DESCRIPTION
**Pull request by Unknownforce351**
This adds OMX Audio support as an alternative to ALSA/PULSE audio using the existing -audio option by specifying the device as either "omxhdmi" or "omxlocal"

### CODE REVIEW

**Comment by Unknownforce351** [comment]
Not sure how all the commits got screwed up, I can fix it to just a single commit, if I need to...

**Comment by irtimmer** [comment]
I've squashed the commits to a single commit and made some small changes (not yet tested). Commit can be found in the omxaudio branch. I have removed some of the config changes because I want to make some changes to them so this could be the default audio output for the Pi. As soon as I've made those changes I will merge it to master.

**Comment by Unknownforce351** [comment]
Well, the code looks fine and should compile, but I don't think audio_device can't be presented to OMX as "sysdefault".  It should either be "hdmi" or "local" for OMX.

OMX's audio_render component can output to HDMI or to analog(local).  This is based on what's provided to the OMX_SetParameter function, which sets the destination of the buffer stream, as an (char*)OMX_CONFIG_BRCMAUDIODESTINATIONTYPE.sName, but the destination must be either hdmi or local, as I don't think it will work otherwise.  There might be a way to detect the output types available and select it based on that, but I'm not sure yet how to do that and it would likely over complicate things and ultimately add another point of possible failure, so maybe make the default "hdmi" and if the user specifies "local" then use that...

in platform.c
`#ifdef HAVE_PI
const char* audio_device = "hdmi";
#else
const char* audio_device = "sysdefault";
#endif`

Or in omx.c, define it if the user hasn't specified it...
`const char* omx_device = "hdmi";
if (strcmp(audio_device, "sysdefault") != 0) omx_device = audio_device;`

One other thing though... by making OMX the default as the code is now, it eliminates anything other than OMX from being a usable audio output device completely if HAVE_PI is true.

To counter that, there would have to be a check in platform.c against audio_device to see determine which AUDIO_RENDERER_CALLBACKS to use.

Personally, I'm fine with dropping ALSA and PULSE usage on the PI, because my whole purpose was that OMX provides me with surround, which I couldn't get with ALSA over HDMI and didn't care to setup PULSE... but I'm not sure how others have their audio device and hardware configs.

**Comment by irtimmer** [comment]
The Raspberry Pi defaults now correctly to the HDMI output so the changed have been merged with commit 5a3665323a3ca1c0e83712cdebb4712105fe408b

**Pull request closed without merging**
